### ISSUE TITLE
[BUG] Album & Year information on Playbar not remaining invisible after restart

### ISSUE THREAD

**Issue by AshleyGainey** [JulienMaille/dribbblish-dynamic-theme#102]
**Describe the bug**
When restarting Spotify after turning off the Album Name and Year information, that information reappears in the Playbar. The setting still says it is switched off when it isn't.

**To Reproduce**
1. Open Spotify
2. Go to Dribblish Settings > Playbar 
3. Turn Off Show Album Info in Playbar
4. Observe the Album Name and Year disappears
5. Press Ctrl + Shift + R or close Spotify and open it back up again
6. Observe the Album Name and Year appearing again after restarts.
7. Go back to the  Dribblish Settings > Playbar > Show Album Info in Playbar and you will see it is turned off when actually it isn't

**Screenshots**
See video attached:
https://user-images.githubusercontent.com/28976914/140907228-eae44326-2c97-4560-b916-f0221d767ecd.mp4

**Desktop Setup**
 - Operating System: Windows 11 (Windows v10.0.22000 - Beta Build)
 - Spotify version: v1.1.69.612
 - Spicetify version: 2.7.2
 - Dribbblish version: v3.1.0-2f706ed

**Logs**
Don't think it is relevant but here are the 8 warnings/2 verbose messages I received:

```EmeEncryptionSchemePolyfill: Waiting to detect encryptionScheme support.
vendor~xpui.js:29 McEncryptionSchemePolyfill: Waiting to detect encryptionScheme support.
spicetifyWrapper.js:845 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
Spicetify._cloneSidebarItem @ spicetifyWrapper.js:845
vendor~xpui.js:29 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2487610)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2489892)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2136447
    at Pa (https://xpui.app.spotify.com/vendor~xpui.js:29:2729463)
    at ks (https://xpui.app.spotify.com/vendor~xpui.js:29:2753315)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:2926970)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2698971)
    at As (https://xpui.app.spotify.com/vendor~xpui.js:29:2753094)
    at Os (https://xpui.app.spotify.com/vendor~xpui.js:29:2737865)
    at vs (https://xpui.app.spotify.com/vendor~xpui.js:29:2736787)
c @ vendor~xpui.js:29
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-playlist.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/644.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/22.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED```

**Comment by SendNukez** [comment]
Will be fixed in the next release. Thank you for reporting this!
