### ISSUE TITLE
AUR's Spotify update breaks the theme

### ISSUE THREAD

**Issue by sicr0** [JulienMaille/dribbblish-dynamic-theme#109]
**Describe the bug**
After the last update to Spotify, the theme sidebar looks different.

**To Reproduce**
1. Update Spotify from the AUR.
2. Open it and see that the default Spotify theme was restored.
3. Run `spicetify backup apply`.
4. Run the DribbblishDynamic theme installer script in the terminal.
5. A part of the output that may be helpful:
```
warning Config "extensions" unchanged: default-dynamic.js is not on the list.
warning Config "extensions" unchanged: dribbblish.js is not on the list.
warning Config "extensions" unchanged: Vibrant.min.js is not on the list.
warning Config "extensions" unchanged: dribbblish-dynamic.js is already in the list.
```

**Screenshots**
![Screenshot_20211112_165120](https://user-images.githubusercontent.com/49662650/141526802-784b9988-1af1-43e3-896c-0daa4e809610.png)

**Desktop Setup**
 - Operating System: Manjaro Linux
 - Spotify version: 1.1.72.439.gc253025e
 - Spicetify version: Dev
 - Dribbblish version: 3.1.1

**Logs**
![Screenshot_20211112_170352](https://user-images.githubusercontent.com/49662650/141528000-90037285-137e-4dbc-931f-48c376a4a094.png)

```console
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2621847)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2624431)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2254849
    at Pa (https://xpui.app.spotify.com/vendor~xpui.js:29:2859649)
    at Is (https://xpui.app.spotify.com/vendor~xpui.js:29:2883381)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:3096964)
    at gr (https://xpui.app.spotify.com/vendor~xpui.js:29:2829185)
    at ks (https://xpui.app.spotify.com/vendor~xpui.js:29:2883160)
    at Os (https://xpui.app.spotify.com/vendor~xpui.js:29:2868039)
    at vs (https://xpui.app.spotify.com/vendor~xpui.js:29:2866961)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2829457
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:3096964)
    at gr (https://xpui.app.spotify.com/vendor~xpui.js:29:2829185)
    at yr (https://xpui.app.spotify.com/vendor~xpui.js:29:2829402)
    at vr (https://xpui.app.spotify.com/vendor~xpui.js:29:2829337)
    at Ss (https://xpui.app.spotify.com/vendor~xpui.js:29:2867460)
    at il (https://xpui.app.spotify.com/vendor~xpui.js:29:2893731)
    at render (https://xpui.app.spotify.com/vendor~xpui.js:29:2896842)
    at https://xpui.app.spotify.com/xpui.js:1:1042488
(anonymous) @ vendor~xpui.js:1
vendor~xpui.js:1 Uncaught TypeError: Cannot read properties of null (reading 'append')
    at e (main.js:255)
    at i (vendor~xpui.js:1)
xpui.js:1 Uncaught (in promise) NotFoundError: GET request to sp://ads/v1/settings/leaderboard failed with status code 404
    at d.onSuccess (xpui.js:1)
    at onSuccess (xpui.js:1)
vendor~xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
sentry.io/api/114855/envelope/?sentry_key=de32132fc06e4b28965ecf25332c3a25&sentry_version=7:1 Failed to load resource: the server responded with a status of 429 (Too Many Requests)
pubads_impl_2021111001.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
about:srcdoc:39 Uncaught TypeError: googletag.defineSlot is not a function
    at about:srcdoc:39
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/696.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-routes-homepage-takeover-ad.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/566.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-home.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
```

**Comment by JulienMaille** [comment]
`Spicetify version: Dev` ???

**Comment by sicr0** [comment]
![Screenshot_20211112_172718](https://user-images.githubusercontent.com/49662650/141530355-b33b1999-0424-4970-b977-b87aa84aa934.png)

I don't know exactly what it means, but the command returns that

**Comment by SendNukez** [comment]
does this happen to other themes too?

**Comment by jitterdev** [comment]
theme works on 2.8.1, but color scheme broken??
![image](https://user-images.githubusercontent.com/64605731/141656253-4163f8b7-ad2f-4e56-949d-192f343da45e.png)

**Comment by JulienMaille** [comment]
This them doesn't have color themes

**Comment by sicr0** [comment]
@JulienMaille I was able to solve it by reinstalling Spotify
