### ISSUE TITLE
Friends activity stops working after click on experimental feature.

### ISSUE THREAD

**Issue by alixti** [JulienMaille/dribbblish-dynamic-theme#133]
**Describe the bug**
Friends activity stops working after click on experimental feature related to friend feed. It begins with no syncing at all and after one week it shows that I'm not sharing my feed despite being activated on Settings (I disabled and enabled it also logged out, reinstalled Spotify and it stopped working even on Spotify without any Spicetify mod. It also stopped working in all my computers). 

**To Reproduce**
1. Go to "**experimental features**".
2. Click on the switch of "**Shows the friend feed**" (you can disable it and then re-enable it).

**Screenshots**
![Screenshot 2021-12-06 200407](https://user-images.githubusercontent.com/67288109/144936808-6d9a0a75-698f-4649-afd2-0bfc4958076b.png)
![image](https://user-images.githubusercontent.com/67288109/144937368-2b940734-f39e-419d-a487-3526fbe2aabf.png)

**Desktop Setup**
- OS: Windows v10.0.19043
- Spotify: v1.1.73.517
- Spicetify: v2.8.3
- Dribbblish: v4.0.0-8ba60b4

**Logs**
```
spicetifyWrapper.js:879 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
Spicetify._cloneSidebarItem @ spicetifyWrapper.js:879
xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/leaderboard
vendor~xpui.js:29 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2669302)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2671886)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2302835
    at Pa (https://xpui.app.spotify.com/vendor~xpui.js:29:2907104)
    at Is (https://xpui.app.spotify.com/vendor~xpui.js:29:2930836)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:3144419)
    at gr (https://xpui.app.spotify.com/vendor~xpui.js:29:2876640)
    at ks (https://xpui.app.spotify.com/vendor~xpui.js:29:2930615)
    at Os (https://xpui.app.spotify.com/vendor~xpui.js:29:2915494)
    at vs (https://xpui.app.spotify.com/vendor~xpui.js:29:2914416)
c @ vendor~xpui.js:29
xpui.js:1 Uncaught (in promise) Error: Slot Request and display failed: Error: LeaderboardManager: cant get slot. Error: Slot Request failed InternalServerError: GET request to sp://ads/v1/ads/leaderboard failed with status code 500
    at xpui.js:1
tracklist-row-song-fallback.svg:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
tracklist-row-song-fallback.svg:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
2TypeError: Cannot read properties of null (reading 'text')
    at Info.set (dribbblish-dynamic.js:54579)
    at dribbblish-dynamic.js:55533
5vendor~xpui.js:29 The buttonLegacy prop has been deprecated. This prop will be removed soon. Please migrate to new button styles by removing this prop.
Read more: https://encore.spotify.net/web/whats-new/green-buttons/?format=web-js
i @ vendor~xpui.js:29
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/696.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/367.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-playlist.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
```

**Comment by alixti** [comment]
Nevermind, seems this is [purely related to Spotify.](https://www.reddit.com/r/spotify/comments/igym56/friend_activity_not_appearing/)
