### ISSUE TITLE
"dribbblish-dynamic.js not installed" message showing up

### ISSUE THREAD

**Issue by Lasermasterluke** [JulienMaille/dribbblish-dynamic-theme#152]
**Describe the bug**
dribbblish-dynamic.js not installed randomly showing up

**To Reproduce**
1. Three dots in the top left
2. Help
3. Third-party software
4. Wait 3 seconds

**Screenshots**
https://gyazo.com/e5a029dc1b98f7bc9240300d14e745dd

**Desktop Setup**
- Operating System: Windows 10
- Spotify: 1.1.72.439
- Spicetify: 2.8.3
- Dribbblish: 4.1.1

**Logs**
```console
spicetifyWrapper.js:879 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
Spicetify._cloneSidebarItem @ spicetifyWrapper.js:879
vendor~xpui.js:29 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2621881)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2624465)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2254849
    at Pa (https://xpui.app.spotify.com/vendor~xpui.js:29:2859683)
    at Is (https://xpui.app.spotify.com/vendor~xpui.js:29:2883415)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:3096998)
    at gr (https://xpui.app.spotify.com/vendor~xpui.js:29:2829219)
    at ks (https://xpui.app.spotify.com/vendor~xpui.js:29:2883194)
    at Os (https://xpui.app.spotify.com/vendor~xpui.js:29:2868073)
    at vs (https://xpui.app.spotify.com/vendor~xpui.js:29:2866995)
c @ vendor~xpui.js:29
xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
guc3-spclient.spotify.com/remote-config-resolver/v2/configs/platforms/web/clients/desktop-ui/property-sets/edacff50be2653d4?installation-id=7a460e52-f88e-4877-b29c-7a365110c2f1&fetch-type=delayed:1 Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/696.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-routes-homepage-takeover-ad.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/566.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-home.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
licenses.html:11 GET https://xpui.app.spotify.com/bundle.js net::ERR_NAME_NOT_RESOLVED
```

**Comment by ps13g** [comment]
Shows up on MacOS also however checking extensions and the config file both contain the dribbblish-dynamic.js file and after reloading the app it still works as intended so I think this is one of those false errors.

**Comment by Lasermasterluke** [comment]
> Shows up on MacOS also however checking extensions and the config file both contain the dribbblish-dynamic.js file and after reloading the app it still works as intended so I think this is one of those false errors.

yeah, dribbblish itself has no issues it's just a weird false error

**Comment by SendNukez** [comment]
Yeah I just checked, this is because the `Third-party software` popup is displaying an iframe, and the css is applied to it, but not the js. I have to see if there is any way to check for an iframe or url inside the css.
