### ISSUE TITLE
No play/pause button

### ISSUE THREAD

**Issue by RadNotRed** [JulienMaille/dribbblish-dynamic-theme#156]
**Describe the bug**
The play/pause button doesn't show
**To Reproduce**
1. Open spotify

**Screenshots**
![image](https://user-images.githubusercontent.com/80015713/150597114-a599b9a7-5d63-4e47-af98-ce714a7deb6c.png)

**Desktop Setup**
OS: Windows v10.0.19043
Spotify: v1.1.77.643
Spicetify: v2.8.4
Dribbblish: v4.1.1-0e50a92

**Logs**

```console
5fluent.js:77 Uncaught TypeError: Cannot read properties of undefined (reading 'Translations')
    at fluent.js:77
vendor~xpui.js:29 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2964053)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2966637)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2536525
    at Ca (https://xpui.app.spotify.com/vendor~xpui.js:29:3208719)
    at ks (https://xpui.app.spotify.com/vendor~xpui.js:29:3232451)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:3447732)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:3178255)
    at Rs (https://xpui.app.spotify.com/vendor~xpui.js:29:3232230)
    at Os (https://xpui.app.spotify.com/vendor~xpui.js:29:3217109)
    at gs (https://xpui.app.spotify.com/vendor~xpui.js:29:3216031)
c @ vendor~xpui.js:29
ic_fluent_play_24_filled.svg:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
expFeatures.js:103 Uncaught TypeError: Cannot read properties of undefined (reading 'properties')
    at waitForRemoteConfigResolver (expFeatures.js:103)
xpui.js:1 Uncaught (in promise) NotFoundError: GET request to sp://ads/v1/settings/leaderboard failed with status code 404
    at d.onSuccess (xpui.js:1)
    at onSuccess (xpui.js:1)
ic_fluent_folder_24_filled.svg:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
vendor~xpui.js:29 The buttonLegacy prop has been deprecated. This prop will be removed soon. Please migrate to new button styles by removing this prop.
Read more: https://encore.spotify.net/web/whats-new/green-buttons/?format=web-js
r @ vendor~xpui.js:29
ic_fluent_pause_16_filled.svg:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/696.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/106.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/376.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
```

**Comment by JulienMaille** [comment]
Can you please try another theme and confirm it's not a more general problem?

**Comment by RadNotRed** [comment]
> Can you please try another theme and confirm it's not a more general problem?

This is not a general problem, there's a lot of random things missing... 
Ex. folder titles, and some more I don't remember off the.top of my head

**Comment by JulienMaille** [comment]
Have you installed the theme from the marketplace, using the powershell script or manually ?

**Comment by RadNotRed** [comment]
> Have you installed the theme from the marketplace, using the powershell script or manually ?

There's a marketplace?
And I installed it manually

**Comment by JulienMaille** [comment]
https://github.com/CharlieS1103/spicetify-marketplace

Can you try our powershell script? I'm unable to reproduce your problem, there may be something wrong with your spicetify setup
