### ISSUE TITLE
New Spotify Update Breaks Hide Upgrade Button Feature

### ISSUE THREAD

**Issue by Rajbir98** [JulienMaille/dribbblish-dynamic-theme#157]
**Describe the bug**

**To Reproduce**
1. Update Spotify, Spicetify, Dribblish Dynamic Theme
2. Open Spotify 
3. Enable Hide Ads
4. Upgrade Button Still Shows

**Screenshots**
![image](https://user-images.githubusercontent.com/84771149/150640276-f9b4b2d5-d63f-4558-ad1c-429a169de4cc.png)

**Desktop Setup**

**Logs**

![image](https://user-images.githubusercontent.com/84771149/150640440-611a1b25-974e-4fa6-899a-ec1d5dcdb8c4.png)

```console
[paste logs here]
```Uncaught TypeError: Cannot set properties of undefined (setting 'value')
    at waitForRemoteConfigResolver (expFeatures.js:71)
spicetifyWrapper.js:879 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
Spicetify._cloneSidebarItem @ spicetifyWrapper.js:879
vendor~xpui.js:29 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2964053)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2966637)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2536525
    at Ca (https://xpui.app.spotify.com/vendor~xpui.js:29:3208719)
    at ks (https://xpui.app.spotify.com/vendor~xpui.js:29:3232451)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:3447732)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:3178255)
    at Rs (https://xpui.app.spotify.com/vendor~xpui.js:29:3232230)
    at Os (https://xpui.app.spotify.com/vendor~xpui.js:29:3217109)
    at gs (https://xpui.app.spotify.com/vendor~xpui.js:29:3216031)
c @ vendor~xpui.js:29
gae2-spclient.spotify.com/quicksilverdev/v2/triggers?trig_type=URI&trig_type=CLIENT_EVENT&ctv_type=web-modal&:1 Failed to load resource: the server responded with a status of 403 ()
xpui.js:1 Uncaught (in promise) NotFoundError: GET request to sp://ads/v1/settings/leaderboard failed with status code 404
    at d.onSuccess (xpui.js:1)
    at onSuccess (xpui.js:1)
xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
gpt.js:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
about:srcdoc:39 Uncaught ReferenceError: googletag is not defined
    at about:srcdoc:39
about:srcdoc:254 Uncaught ReferenceError: googletag is not defined
    at about:srcdoc:254
hidePodcasts.js:47 / <section data-testid=​"home-page">​…​</section>​
hidePodcasts.js:134 Tagging carousel: Spirit Of Republic Day
hidePodcasts.js:134 Tagging carousel: Episodes for you
hidePodcasts.js:134 Tagging carousel: Your shows
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/696.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-routes-homepage-takeover-ad.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-home.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED

**Comment by JulienMaille** [comment]
It's probably a css mapping issue with spicetify rather that this theme

**Comment by Rajbir98** [comment]
the problem occurs here too https://github.com/Daksh777/SpotifyNoPremium/issues/41#issue-1111550824

**Comment by Rajbir98** [comment]
reinstalling Spotify fixes the problem
