### ISSUE TITLE
Windows Install not properly installing 

### ISSUE THREAD

**Issue by ChoogleGrome** [JulienMaille/dribbblish-dynamic-theme#22]
Title. Logs from the .ps1 script as well as logs from spotify inlcluded

![image](https://user-images.githubusercontent.com/28058286/125201632-243c0700-e2af-11eb-8a11-77d36b9cfe7e.png)

```
vendor~xpui.js:29 [Deprecation] SharedArrayBuffer will require cross-origin isolation as of M91, around May 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.
7673 @ vendor~xpui.js:29
dribbblish-dynamic.js:151 Uncaught ReferenceError: waitForElement is not defined
    at dribbblish-dynamic.js:151
xpui.js:1 AllboardingAPINoOp.shouldShowOnLoad
xpui.js:1 No container found for fullscreen video!
(anonymous) @ xpui.js:1
vendor~xpui.js:29 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2364353)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2366635)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:1799495
    at ka (https://xpui.app.spotify.com/vendor~xpui.js:29:2647517)
    at Ps (https://xpui.app.spotify.com/vendor~xpui.js:29:2671369)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:2873919)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2617025)
    at Cs (https://xpui.app.spotify.com/vendor~xpui.js:29:2671148)
    at ws (https://xpui.app.spotify.com/vendor~xpui.js:29:2655919)
    at ys (https://xpui.app.spotify.com/vendor~xpui.js:29:2654841)
c @ vendor~xpui.js:29
vendor~xpui.js:1 [transport.transport] Auth header setting awaiting authentication.
vendor~xpui.js:1 [transport.transport] Auth header setting awaiting authentication.
vendor~xpui.js:1 [transport.transport] Auth header setting awaiting authentication.
vendor~xpui.js:1 [transport.transport] Auth header setting awaiting authentication.
vendor~xpui.js:1 [transport.transport] Auth header set after authentication.
vendor~xpui.js:1 [transport.transport] Auth header set after authentication.
vendor~xpui.js:1 [transport.transport] Auth header set after authentication.
vendor~xpui.js:1 [transport.transport] Auth header set after authentication.
vendor~xpui.js:1 [transport.http.fetch] Could not parse response as JSON: SyntaxError: Unexpected end of JSON input
    at vendor~xpui.js:29
_print @ vendor~xpui.js:1
vendor~xpui.js:1 [transport.http.fetch] Could not parse response as JSON: SyntaxError: Unexpected end of JSON input
    at vendor~xpui.js:29
_print @ vendor~xpui.js:1
vendor~xpui.js:1 [transport.http.fetch] Could not parse response as JSON: SyntaxError: Unexpected end of JSON input
    at vendor~xpui.js:29
_print @ vendor~xpui.js:1
vendor~xpui.js:1 [transport.http.fetch] Could not parse response as JSON: SyntaxError: Unexpected end of JSON input
    at vendor~xpui.js:29
_print @ vendor~xpui.js:1
vendor~xpui.js:1 [transport.http.fetch] Could not parse response as JSON: SyntaxError: Unexpected end of JSON input
_print @ vendor~xpui.js:1
vendor~xpui.js:1 [transport.http.fetch] Could not parse response as JSON: SyntaxError: Unexpected end of JSON input
    at vendor~xpui.js:29
_print @ vendor~xpui.js:1
vendor~xpui.js:1 [transport.http.fetch] Could not parse response as JSON: SyntaxError: Unexpected end of JSON input
    at vendor~xpui.js:29
_print @ vendor~xpui.js:1
vendor~xpui.js:1 [transport.http.fetch] Could not parse response as JSON: SyntaxError: Unexpected end of JSON input
    at vendor~xpui.js:29
_print @ vendor~xpui.js:1
vendor~xpui.js:1 [transport.http.fetch] Could not parse response as JSON: SyntaxError: Unexpected end of JSON input
_print @ vendor~xpui.js:1
vendor~xpui.js:1 [transport.http.fetch] Could not parse response as JSON: SyntaxError: Unexpected end of JSON input
_print @ vendor~xpui.js:1
vendor~xpui.js:1 [transport.http.fetch] Could not parse response as JSON: SyntaxError: Unexpected end of JSON input
_print @ vendor~xpui.js:1
vendor~xpui.js:1 [transport.http.fetch] Could not parse response as JSON: SyntaxError: Unexpected end of JSON input
_print @ vendor~xpui.js:1
vendor~xpui.js:1 [transport.http.fetch] Could not parse response as JSON: SyntaxError: Unexpected end of JSON input
_print @ vendor~xpui.js:1
vendor~xpui.js:1 [transport.http.fetch] Could not parse response as JSON: SyntaxError: Unexpected end of JSON input
_print @ vendor~xpui.js:1
vendor~xpui.js:1 [transport.http.fetch] Could not parse response as JSON: SyntaxError: Unexpected end of JSON input
    at vendor~xpui.js:29
_print @ vendor~xpui.js:1
vendor~xpui.js:1 [transport.http.fetch] Could not parse response as JSON: SyntaxError: Unexpected end of JSON input
_print @ vendor~xpui.js:1
vendor~xpui.js:1 [transport.http.fetch] Could not parse response as JSON: SyntaxError: Unexpected end of JSON input
_print @ vendor~xpui.js:1
vendor~xpui.js:1 [transport.http.fetch] Could not parse response as JSON: SyntaxError: Unexpected end of JSON input
_print @ vendor~xpui.js:1
vendor~xpui.js:1 [transport.http.fetch] Could not parse response as JSON: SyntaxError: Unexpected end of JSON input
_print @ vendor~xpui.js:1
vendor~xpui.js:1 [transport.http.fetch] Could not parse response as JSON: SyntaxError: Unexpected end of JSON input
    at vendor~xpui.js:29
_print @ vendor~xpui.js:1
vendor~xpui.js:1 [transport.http.fetch] Could not parse response as JSON: SyntaxError: Unexpected end of JSON input
_print @ vendor~xpui.js:1
vendor~xpui.js:1 [transport.http.fetch] Could not parse response as JSON: SyntaxError: Unexpected end of JSON input
    at vendor~xpui.js:29
_print @ vendor~xpui.js:1
vendor~xpui.js:1 [transport.http.fetch] Could not parse response as JSON: SyntaxError: Unexpected end of JSON input
    at vendor~xpui.js:29
_print @ vendor~xpui.js:1
vendor~xpui.js:1 [transport.http.fetch] Could not parse response as JSON: SyntaxError: Unexpected end of JSON input
_print @ vendor~xpui.js:1
vendor~xpui.js:1 [transport.http.fetch] Could not parse response as JSON: SyntaxError: Unexpected end of JSON input
_print @ vendor~xpui.js:1
vendor~xpui.js:1 [transport.http.fetch] Could not parse response as JSON: SyntaxError: Unexpected end of JSON input
_print @ vendor~xpui.js:1
vendor~xpui.js:1 [transport.http.fetch] Could not parse response as JSON: SyntaxError: Unexpected end of JSON input
_print @ vendor~xpui.js:1
vendor~xpui.js:1 [transport.http.fetch] Could not parse response as JSON: SyntaxError: Unexpected end of JSON input
_print @ vendor~xpui.js:1
vendor~xpui.js:1 [transport.http.fetch] Could not parse response as JSON: SyntaxError: Unexpected end of JSON input
    at vendor~xpui.js:29
_print @ vendor~xpui.js:1
vendor~xpui.js:1 [transport.http.fetch] Could not parse response as JSON: SyntaxError: Unexpected end of JSON input
    at vendor~xpui.js:29
_print @ vendor~xpui.js:1
vendor~xpui.js:1 [transport.http.fetch] Could not parse response as JSON: SyntaxError: Unexpected end of JSON input
    at vendor~xpui.js:29
_print @ vendor~xpui.js:1
vendor~xpui.js:1 [transport.http.fetch] Could not parse response as JSON: SyntaxError: Unexpected end of JSON input
_print @ vendor~xpui.js:1
vendor~xpui.js:1 [transport.http.fetch] Could not parse response as JSON: SyntaxError: Unexpected end of JSON input
    at vendor~xpui.js:29
_print @ vendor~xpui.js:1
DevTools failed to load SourceMap: Could not load content for https://xpui.app.spotify.com/service-worker.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://xpui.app.spotify.com/766.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://xpui.app.spotify.com/xpui-routes-collection-songs.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
```

**Comment by ChoogleGrome** [comment]
I understand #21 has the exact same issue as what im having however the fix is not highlighted in that issue

**Comment by JulienMaille** [comment]
Please share the content of `config-xpui.ini`. What's that custom terminal you are using?

**Comment by ChoogleGrome** [comment]
`config-xpui.ini` :
```ini
[Setting]
spotify_path            = C:\Users\aquif\AppData\Roaming\Spotify
color_scheme            = base
inject_css              = 1
replace_colors          = 1
overwrite_assets        = 1
prefs_path              = C:\Users\aquif\AppData\Roaming\Spotify\prefs
current_theme           = DribbblishDynamic
spotify_launch_flags    = 
check_spicetify_upgrade = 0

[Preprocesses]
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1

[AdditionalOptions]
extensions     = webnowplaying.js|dribbblish-dynamic.js|dribbblish.js|Vibrant.min.js
custom_apps    = 
sidebar_config = 1
home_config    = 1

[Patch]
xpui.js_find_8008 = ,(\w+=)32,
xpui.js_repl_8008 = ,${1}56,

; DO NOT CHANGE!
[Backup]
version = 1.1.62.583.gdac868ed
with    = 2.5.0
```

The terminal is just Windows Terminal running Powershell 7 with a custom theme

**Comment by JulienMaille** [comment]
Try swapping dribblish js files in `extensions     = webnowplaying.js|dribbblish-dynamic.js|dribbblish.js|Vibrant.min.js
`

**Comment by ChoogleGrome** [comment]
> Try swapping dribblish js files in `extensions = webnowplaying.js|dribbblish-dynamic.js|dribbblish.js|Vibrant.min.js `

this fixed it, thanks
