### ISSUE TITLE
[BUG] Theme css is glitched out

### ISSUE THREAD

**Issue by KarkaLT** [JulienMaille/dribbblish-dynamic-theme#32]
**Describe the bug**

- Play button doesn't have icon
- When large album cover is shown, small one is also showing.
- Hovering over slider shows empty view
- Duration isn't showing
- Playlist icons aren't showing

**To Reproduce**
Completely reinstall spicetify and install theme with command.

**Screenshots**
![Ekrano nuotrauka 2021-08-26 221723](https://user-images.githubusercontent.com/45921825/131023276-159d0643-451d-47cc-ac5a-506ac35eec3b.png)
![Ekrano nuotrauka 2021-08-26 222153](https://user-images.githubusercontent.com/45921825/131023406-a363d336-8ae9-422b-a73e-44d2984fc24a.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 22000.160

**Logs**

```console
vendor~xpui.js:1 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at u (https://xpui.app.spotify.com/vendor~xpui.js:29:2781990)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2784272)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2090235
    at ka (https://xpui.app.spotify.com/vendor~xpui.js:29:3061153)
    at Ps (https://xpui.app.spotify.com/vendor~xpui.js:29:3085005)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:3296794)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:3030661)
    at Is (https://xpui.app.spotify.com/vendor~xpui.js:29:3084784)
    at ws (https://xpui.app.spotify.com/vendor~xpui.js:29:3069555)
    at vs (https://xpui.app.spotify.com/vendor~xpui.js:29:3068477)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:3030933
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:3296794)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:3030661)
    at yi (https://xpui.app.spotify.com/vendor~xpui.js:29:3030878)
    at vi (https://xpui.app.spotify.com/vendor~xpui.js:29:3030813)
    at hs (https://xpui.app.spotify.com/vendor~xpui.js:29:3067470)
    at Object.enqueueSetState (https://xpui.app.spotify.com/vendor~xpui.js:29:3035626)
    at r.A.setState (https://xpui.app.spotify.com/vendor~xpui.js:29:3220531)
    at r.<anonymous> (https://xpui.app.spotify.com/xpui.js:1:725072)
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:3265208)
    at Generator._invoke (https://xpui.app.spotify.com/vendor~xpui.js:29:3264996)
    at Generator.next (https://xpui.app.spotify.com/vendor~xpui.js:29:3265637)
    at r (https://xpui.app.spotify.com/vendor~xpui.js:29:3621511)
    at s (https://xpui.app.spotify.com/vendor~xpui.js:29:3621714)
(anonymous) @ vendor~xpui.js:1
vendor~xpui.js:1 Uncaught TypeError: Cannot read property 'offsetLeft' of null
    at updateProgTime (dribbblish.js:157)
    at Dribbblish (dribbblish.js:172)
    at r (vendor~xpui.js:1)
​ [GPT] Invalid argument: PubAdsService.setRequestNonPersonalizedAds("0"). Valid values: 0,1.
Fu.log @ pubads_impl_2021081901.js:6
​ [GPT] Invalid argument: PubadsService.setTagForUnderAgeOfConsent("1"). Valid values: 2,0,1.
Fu.log @ pubads_impl_2021081901.js:6
3vendor~xpui.js:1 Error: SUB request to sp://player/v2/main?reverse_cap=2&future_cap=2 failed with exception 'Cannot read property 'offsetLeft' of null'
    at e.value (xpui.js:1)
    at onSuccess (xpui.js:1)
(anonymous) @ vendor~xpui.js:1
vendor~xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/leaderboard
​ [GPT] Invalid argument: PubAdsService.setRequestNonPersonalizedAds("0"). Valid values: 0,1.
Fu.log @ pubads_impl_2021081901.js:6
​ [GPT] Invalid argument: PubadsService.setTagForUnderAgeOfConsent("1"). Valid values: 2,0,1.
Fu.log @ pubads_impl_2021081901.js:6
13vendor~xpui.js:1 Error: SUB request to sp://player/v2/main?reverse_cap=2&future_cap=2 failed with exception 'Cannot read property 'offsetLeft' of null'
    at e.value (xpui.js:1)
    at onSuccess (xpui.js:1)
(anonymous) @ vendor~xpui.js:1
vendor~xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/leaderboard
vendor~xpui.js:1 Error: SUB request to sp://player/v2/main?reverse_cap=2&future_cap=2 failed with exception 'Cannot read property 'offsetLeft' of null'
    at e.value (xpui.js:1)
    at onSuccess (xpui.js:1)
(anonymous) @ vendor~xpui.js:1
​ [GPT] Invalid argument: PubAdsService.setRequestNonPersonalizedAds("0"). Valid values: 0,1.
Fu.log @ pubads_impl_2021081901.js:6
​ [GPT] Invalid argument: PubadsService.setTagForUnderAgeOfConsent("1"). Valid values: 2,0,1.
Fu.log @ pubads_impl_2021081901.js:6
vendor~xpui.js:1 Error: SUB request to sp://player/v2/main?reverse_cap=2&future_cap=2 failed with exception 'Cannot read property 'offsetLeft' of null'
    at e.value (xpui.js:1)
    at onSuccess (xpui.js:1)
(anonymous) @ vendor~xpui.js:1
vendor~xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/leaderboard
pubads_impl_2021081901.js:6 [GPT] Invalid argument: PubAdsService.setRequestNonPersonalizedAds("0"). Valid values: 0,1.
Fu.log @ pubads_impl_2021081901.js:6
pubads_impl_2021081901.js:6 [GPT] Invalid argument: PubadsService.setTagForUnderAgeOfConsent("1"). Valid values: 2,0,1.
Fu.log @ pubads_impl_2021081901.js:6
4vendor~xpui.js:1 Error: SUB request to sp://player/v2/main?reverse_cap=2&future_cap=2 failed with exception 'Cannot read property 'offsetLeft' of null'
    at e.value (xpui.js:1)
    at onSuccess (xpui.js:1)
(anonymous) @ vendor~xpui.js:1
vendor~xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
pubads_impl_2021081901.js:6 [GPT] Invalid argument: PubAdsService.setRequestNonPersonalizedAds("0"). Valid values: 0,1.
Fu.log @ pubads_impl_2021081901.js:6
pubads_impl_2021081901.js:6 [GPT] Invalid argument: PubadsService.setTagForUnderAgeOfConsent("1"). Valid values: 2,0,1.
Fu.log @ pubads_impl_2021081901.js:6
vendor~xpui.js:1 no-ad
(anonymous) @ vendor~xpui.js:1
4vendor~xpui.js:1 Error: SUB request to sp://player/v2/main?reverse_cap=2&future_cap=2 failed with exception 'Cannot read property 'offsetLeft' of null'
    at e.value (xpui.js:1)
    at onSuccess (xpui.js:1)
(anonymous) @ vendor~xpui.js:1
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/service-worker.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/22.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-playlist.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-routes-homepage-takeover-ad.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-home.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/998.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
15vendor~xpui.js:1 Error: SUB request to sp://player/v2/main?reverse_cap=2&future_cap=2 failed with exception 'Cannot read property 'offsetLeft' of null'
    at e.value (xpui.js:1)
    at onSuccess (xpui.js:1)
```

**Comment by ccrsxx** [comment]
Same, it happens after I update the theme. Any idea how to fix it?

**Comment by JulienMaille** [comment]
Please refer to https://github.com/morpheusthewhite/spicetify-themes/issues/507 tldr; spicetify is currently broken
