### ISSUE TITLE
[BUG] Dark mode not working

### ISSUE THREAD

**Issue by BlueskyFR** [JulienMaille/dribbblish-dynamic-theme#34]
**Describe the bug**

When enabling the dark mode, nothing happens.

**To Reproduce**
- Enable the dark mode in the options at the top right.

**Screenshots**
![image](https://user-images.githubusercontent.com/25421460/133894115-1e989e19-b315-4fad-b824-92c1d106f03f.png)

**Desktop (please complete the following information):**
 - OS: Manjaro, i3 edition
 - Version: latest

**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtools` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.

```console
vendor~xpui.js:29 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2656773)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2659055)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2091056
    at ka (https://xpui.app.spotify.com/vendor~xpui.js:29:2946534)
    at Ps (https://xpui.app.spotify.com/vendor~xpui.js:29:2970386)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:3190652)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2916042)
    at Is (https://xpui.app.spotify.com/vendor~xpui.js:29:2970165)
    at ws (https://xpui.app.spotify.com/vendor~xpui.js:29:2954936)
    at vs (https://xpui.app.spotify.com/vendor~xpui.js:29:2953858)
c @ vendor~xpui.js:29
xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
xpui.js:1 Uncaught (in promise) Error: GET request to sp://ads/v1/ads/hpto failed with status code 500
    at s.onSuccess (xpui.js:1)
    at onSuccess (xpui.js:1)
spotify:image:ab67616d0000485190378cdcde9552b3550bf3dc:1 Failed to load resource: the server responded with a status of 404 (Not Found)
spotify:image:ab67616d00004851b725b69e52c331f36fa27f8c:1 Failed to load resource: the server responded with a status of 404 (Not Found)
spotify:image:ab67616d00004851babff6e2dce742ba6a9ffed2:1 Failed to load resource: the server responded with a status of 404 (Not Found)
spotify:image:ab67616d000048514e81183d5c33a909263a1b74:1 Failed to load resource: the server responded with a status of 404 (Not Found)
spotify:image:ab67616d0000485126c9f9ab5d45f43f526e1a4e:1 Failed to load resource: the server responded with a status of 404 (Not Found)
spotify:image:ab67616d00004851754c4f7b3c75446a5c378ea8:1 Failed to load resource: the server responded with a status of 404 (Not Found)
spotify:image:ab67616d00004851ac5897f8e8a26ebaf3caebb9:1 Failed to load resource: the server responded with a status of 404 (Not Found)
spotify:image:ab67616d0000485193b1fe8e7cca0547cba236ea:1 Failed to load resource: the server responded with a status of 404 (Not Found)
spotify:image:ab67616d0000485143f22199ba8d68aa63e05fe7:1 Failed to load resource: the server responded with a status of 404 (Not Found)
spotify:image:ab67616d000048519500bcbf84e5887578539d12:1 Failed to load resource: the server responded with a status of 404 (Not Found)
spotify:image:ab67616d000048516285414f55b7a4332719556a:1 Failed to load resource: the server responded with a status of 404 (Not Found)
spotify:image:ab67616d000048510814bb01d7a765365d444a0c:1 Failed to load resource: the server responded with a status of 404 (Not Found)
spotify:image:ab67616d0000485164fee3b93a18e172541090d7:1 Failed to load resource: the server responded with a status of 404 (Not Found)
spotify:image:ab67616d00004851cd7b367f1bd3334bea9e4629:1 Failed to load resource: the server responded with a status of 404 (Not Found)
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/service-worker.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/451.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-artist.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-routes-homepage-takeover-ad.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-offline-browse.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-home.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/998.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/22.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-playlist.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
```

**Comment by JulienMaille** [comment]
Please check: spotify version, spicetify version, this theme version

**Comment by BlueskyFR** [comment]
Spotify version: AUR latest
spicetify version: 2.6.4 (just upgraded, nothing changed)
This theme version: latest, I installed it an hour ago from the bash install script

**Comment by JulienMaille** [comment]
Maybe the Linux version is lagging, dark mode works fine on Windows

**Comment by matzyy** [comment]
I just looked at it a bit.
There seems to be some king of bug with the Spicetify.Menu.Item at [this line](https://github.com/JulienMaille/dribbblish-dynamic-theme/blob/127f604dd6e5ae7a215e0480177da55c1c05672c/dribbblish-dynamic.js#L187].
Btw. the "Right expanded cover" doesn't work for me either. So it is most likely something with the action on click in the menu.

Temporary solution: as of spotify uses some older version of a chromium embedded framework, you can start it with `spotify --force-dark-mode &`.

**Comment by Macilvoy** [comment]
Spotify: 1.1.68.632.g2b11de83
Spicetify:  2.6.4

same problem

**Comment by JulienMaille** [comment]
I think you may want to reinstall spotify and then spicetify, both menu items do work fine on my setup.

**Comment by BlueskyFR** [comment]
> I think you may want to reinstall spotify and then spicetify, both menu items do work fine on my setup.

Already did that, same problem: can reproduce every time.

**Comment by Macilvoy** [comment]
> I think you may want to reinstall spotify and then spicetify, both menu items do work fine on my setup.

I literally did it before writing my first comment.

**Comment by JulienMaille** [comment]
I've read on discord that they recommend to completely remove spicetify-cli and .spicetify folder, then reinstall
