### ISSUE TITLE
[BUG] Buttons and texts are underlaid songs.

### ISSUE THREAD

**Issue by kyrie25** [JulienMaille/dribbblish-dynamic-theme#52]
**Describe the bug**
Buttons and texts at the bottom of lists are underlaid songs.

**To Reproduce**
Install theme from Powershell command.
Text appears under songs when launched.

**Screenshots**
![image](https://user-images.githubusercontent.com/77577746/136224997-53b6f50c-9eee-44d0-b958-e0139cdb162e.png)
![image](https://user-images.githubusercontent.com/77577746/136225092-6fc38e50-f3e4-4c08-ab76-0fb77fdde7e2.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Insider Preview Dev build 22471
 - Version: 2.3

**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtools` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.

```console
vendor~xpui.js:1 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2487610)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2489892)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2136447
    at Pa (https://xpui.app.spotify.com/vendor~xpui.js:29:2729463)
    at ks (https://xpui.app.spotify.com/vendor~xpui.js:29:2753315)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:2926970)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2698971)
    at As (https://xpui.app.spotify.com/vendor~xpui.js:29:2753094)
    at Os (https://xpui.app.spotify.com/vendor~xpui.js:29:2737865)
    at vs (https://xpui.app.spotify.com/vendor~xpui.js:29:2736787)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2699243
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:2926970)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2698971)
    at yi (https://xpui.app.spotify.com/vendor~xpui.js:29:2699188)
    at vi (https://xpui.app.spotify.com/vendor~xpui.js:29:2699123)
    at Ss (https://xpui.app.spotify.com/vendor~xpui.js:29:2737286)
    at rl (https://xpui.app.spotify.com/vendor~xpui.js:29:2763699)
    at render (https://xpui.app.spotify.com/vendor~xpui.js:29:2766810)
    at https://xpui.app.spotify.com/xpui.js:1:1030536
(anonymous) @ vendor~xpui.js:1
vendor~xpui.js:1 Cannot read property 'featureVersion' of undefined
sentry.io/api/114855/envelope/?sentry_key=de32132fc06e4b28965ecf25332c3a25&sentry_version=7:1 Failed to load resource: the server responded with a status of 429 (Too Many Requests)
vendor~xpui.js:1 Cannot read property 'featureVersion' of undefined
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/451.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-artist.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/644.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
```

**Comment by SendNukez** [comment]
Ok, will push when #51 is resolved as well. Thank you for reporting this.
