### ISSUE TITLE
[BUG] Spotify UI breaks after advertisements

### ISSUE THREAD

**Issue by sicr0** [JulienMaille/dribbblish-dynamic-theme#63]
**Describe the bug**
The Spotify UI get squeezed up and in the remaining blank space appears the background (tt is hard to describe, watch the picture below to understand better).

**To Reproduce**
I am not exactly sure how to reproduce it, the only thing I know is that it happens after a while and that it always happens when Spotify is minimized.

**Screenshots**
![Screenshot_20211009_231636](https://user-images.githubusercontent.com/49662650/136678872-0e0f19c8-6b6c-4d4f-b44f-af252b40e428.png)

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Version 21.1.5 Pahvo

**Logs**
I have the AUR Spicetify version, for some reason the DevTools does not appear when i press <kbd>Ctrl + Shift + I</kbd>.

**Comment by SendNukez** [comment]
Might be because of the same reasons as [this](https://github.com/JulienMaille/dribbblish-dynamic-theme/pull/39#issuecomment-927365059) @JulienMaille?

Also to enable devtools you have to run `spicetify enable-devtools`.

**Comment by SendNukez** [comment]
Oh, that's a typo in the issue template then. You can also try to right click somewhere and click "Show DevTools" (only works in spots the spotify context menu dosen't open).

**Comment by SendNukez** [comment]
Thank you.

**Comment by sicr0** [comment]
Just happened again, this are the console's log screenshots I have taken:
![Screenshot_20211010_055348](https://user-images.githubusercontent.com/49662650/136689178-14befc94-0207-4bc9-9f48-123637ef82b4.png)
![Screenshot_20211010_055353](https://user-images.githubusercontent.com/49662650/136689179-00ad83fd-583d-46d3-ad2f-64f8f45a73c8.png)

I also copied the text, this is what it says:
```
vendor~xpui.js:1 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2353172)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2355454)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2048746
    at Pa (https://xpui.app.spotify.com/vendor~xpui.js:29:2595327)
    at As (https://xpui.app.spotify.com/vendor~xpui.js:29:2619179)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:2793496)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2564835)
    at ks (https://xpui.app.spotify.com/vendor~xpui.js:29:2618958)
    at Os (https://xpui.app.spotify.com/vendor~xpui.js:29:2603729)
    at vs (https://xpui.app.spotify.com/vendor~xpui.js:29:2602651)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2565107
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:2793496)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2564835)
    at yi (https://xpui.app.spotify.com/vendor~xpui.js:29:2565052)
    at vi (https://xpui.app.spotify.com/vendor~xpui.js:29:2564987)
    at Es (https://xpui.app.spotify.com/vendor~xpui.js:29:2603150)
    at rl (https://xpui.app.spotify.com/vendor~xpui.js:29:2629563)
    at render (https://xpui.app.spotify.com/vendor~xpui.js:29:2632674)
    at https://xpui.app.spotify.com/xpui.js:1:1034419
xpui.js:1 Uncaught (in promise) Error: GET request to sp://ads/v1/settings/leaderboard failed with status code 404
    at l.onSuccess (xpui.js:1)
    at onSuccess (xpui.js:1)
pubads_impl_2021100401.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
vendor~xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
vendor~xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/leaderboard
pubads_impl_2021100401.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
about:srcdoc:39 Uncaught TypeError: googletag.defineSlot is not a function
    at about:srcdoc:39
pubads_impl_2021100401.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
16
vendor~xpui.js:1 Error: SUB request to sp://ads/v1/slots/stream failed with exception '[VTO] Unsupported event type: discard'
    at l.onSuccess (xpui.js:1)
    at onSuccess (xpui.js:1)
pagead2.googlesyndic…YswMyCDtxPEJexEzV:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
7
vendor~xpui.js:1 Error: SUB request to sp://ads/v1/slots/stream failed with exception '[VTO] Unsupported event type: discard'
    at l.onSuccess (xpui.js:1)
    at onSuccess (xpui.js:1)
pagead2.googlesyndic…YswMyCHiog1giIbyL:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
2
vendor~xpui.js:1 Error: SUB request to sp://ads/v1/slots/stream failed with exception '[VTO] Unsupported event type: discard'
    at l.onSuccess (xpui.js:1)
    at onSuccess (xpui.js:1)
Vibrant.min.js:22 Uncaught (in promise) DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.
    at b.getImageData (https://xpui.app.spotify.com/extensions/Vibrant.min.js:22:529)
    at new b (https://xpui.app.spotify.com/extensions/Vibrant.min.js:13:89)
    at pickCoverColor (https://xpui.app.spotify.com/extensions/dribbblish-dynamic.js:345:20)
    at https://xpui.app.spotify.com/extensions/dribbblish-dynamic.js:369:76
    at waitForElement (https://xpui.app.spotify.com/extensions/dribbblish.js:323:9)
    at hookCoverChange (https://xpui.app.spotify.com/extensions/dribbblish-dynamic.js:367:5)
    at songchange (https://xpui.app.spotify.com/extensions/dribbblish-dynamic.js:303:5)
    at r (https://xpui.app.spotify.com/vendor~xpui.js:1:191324)
Vibrant.min.js:22 Uncaught (in promise) DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.
    at b.getImageData (https://xpui.app.spotify.com/extensions/Vibrant.min.js:22:529)
    at new b (https://xpui.app.spotify.com/extensions/Vibrant.min.js:13:89)
    at pickCoverColor (https://xpui.app.spotify.com/extensions/dribbblish-dynamic.js:345:20)
    at https://xpui.app.spotify.com/extensions/dribbblish-dynamic.js:369:76
    at waitForElement (https://xpui.app.spotify.com/extensions/dribbblish.js:323:9)
    at hookCoverChange (https://xpui.app.spotify.com/extensions/dribbblish-dynamic.js:367:5)
    at Array.songchange (https://xpui.app.spotify.com/extensions/dribbblish-dynamic.js:303:5)
    at Object.dispatchEvent (https://xpui.app.spotify.com/helper/spicetifyWrapper.js:18:29)
    at https://xpui.app.spotify.com/helper/spicetifyWrapper.js:172:34
    at https://xpui.app.spotify.com/xpui.js:1:1239610
    at l.onSuccess (https://xpui.app.spotify.com/xpui.js:1:1240815)
    at onSuccess (https://xpui.app.spotify.com/xpui.js:1:1240647)
6
vendor~xpui.js:1 Error: SUB request to sp://ads/v1/slots/stream failed with exception '[VTO] Unsupported event type: discard'
    at l.onSuccess (xpui.js:1)
    at onSuccess (xpui.js:1)
pagead2.googlesyndic…YswMyCPT91ojdK-WG:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
5
vendor~xpui.js:1 Error: SUB request to sp://ads/v1/slots/stream failed with exception '[VTO] Unsupported event type: discard'
    at l.onSuccess (xpui.js:1)
    at onSuccess (xpui.js:1)
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/service-worker.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/22.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/644.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-collection-songs.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-routes-homepage-takeover-ad.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-home.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/754.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
```
﻿

**Comment by sicr0** [comment]
Ok I will do it. I will update if the error stops showing up

**Comment by sicr0** [comment]
Since I applied the fix the theme went perfectly. Thank you!

**Comment by SendNukez** [comment]
A friend of mine had it appear, I don't know why this is only happen on some occasions.

**Comment by JulienMaille** [comment]
This was triggered by vibrant being called on an unloaded image. If we move to chroma, this should go away

**Comment by JulienMaille** [comment]
@sicr0 feel free to reopen if you still have issues with 3.1.0
