### ISSUE TITLE
[BUG] Dribblish Dynamic without the dynamic

### ISSUE THREAD

**Issue by lionel175** [JulienMaille/dribbblish-dynamic-theme#75]
**Describe the bug**
I installed the dynamic theme but none of the parts that are "dynamic" are working its just constantly in the red theme the spotifynocontrol is also not working at all for me. I have reinstalled both spotify and spcietify so I that can't be a fix

**To Reproduce**
I am using the newest version of spicetify and spotify so that could be an issue

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H1

```console
vendor~xpui.js:1 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2492650)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2495234)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2135437
    at Pa (https://xpui.app.spotify.com/vendor~xpui.js:29:2730529)
    at ks (https://xpui.app.spotify.com/vendor~xpui.js:29:2754261)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:2967853)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2700065)
    at Is (https://xpui.app.spotify.com/vendor~xpui.js:29:2754040)
    at Os (https://xpui.app.spotify.com/vendor~xpui.js:29:2738919)
    at vs (https://xpui.app.spotify.com/vendor~xpui.js:29:2737841)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2700337
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:2967853)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2700065)
    at yi (https://xpui.app.spotify.com/vendor~xpui.js:29:2700282)
    at vi (https://xpui.app.spotify.com/vendor~xpui.js:29:2700217)
    at Ss (https://xpui.app.spotify.com/vendor~xpui.js:29:2738340)
    at rl (https://xpui.app.spotify.com/vendor~xpui.js:29:2764611)
    at render (https://xpui.app.spotify.com/vendor~xpui.js:29:2767722)
    at https://xpui.app.spotify.com/xpui.js:1:997568
(anonymous) @ vendor~xpui.js:1
sentry.io/api/114855/envelope/?sentry_key=de32132fc06e4b28965ecf25332c3a25&sentry_version=7:1 Failed to load resource: the server responded with a status of 429 (Too Many Requests)
vendor~xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
tracklist-row-song-fallback.svg:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
tracklist-row-song-fallback.svg:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
tracklist-row-song-fallback.svg:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
sentry.io/api/114855/envelope/?sentry_key=de32132fc06e4b28965ecf25332c3a25&sentry_version=7:1 Failed to load resource: the server responded with a status of 429 (Too Many Requests)
vendor~xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
tracklist-row-song-fallback.svg:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
tracklist-row-song-fallback.svg:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
tracklist-row-song-fallback.svg:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/644.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-routes-homepage-takeover-ad.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/596.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-home.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/22.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-playlist.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
```

**Comment by HazemDa1st** [comment]
make sure to that {Vibrant.min.js} is installed with the extinctions.
